### ISSUE TITLE
@Grid removal of line items is throwing console error

### ISSUE THREAD

**Issue by lopezton-anthem** [openanthem/nimbus-core#540]
# Issue Details

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
When adding rows to a `@Grid`, navigating away from that page and then coming back, if those entries are removed from the `@Grid` component, a console browser error is thrown.

## Expected Behavior
Entries should be able to be removed without error.

### Steps to Reproduce
1. Configure a transient `@Grid`
2. Load the page with that transient grid
3. Add an entry
4. Navigate to a different view domain
5. Navigate back to the view domain with `@Grid`
6. Remove the entry

Observe:
```json
 {
"stack":"TypeError: Cannot read property 'vlm' of undefined
    at Object.updateDirectives (http://localhost:8082/petclinic/main.28aace44eda54d8098cf.js:1:2460097)
    at Object.updateDirectives (http://localhost:8082/petclinic/main.28aace44eda54d8098cf.js:1:456269)
    at Zy (http://localhost:8082/petclinic/main.28aace44eda54d8098cf.js:1:448038)
    at lv (http://localhost:8082/petclinic/main.28aace44eda54d8098cf.js:1:454982)
    at ov (http://localhost:8082/petclinic/main.28aace44eda54d8098cf.js:1:454645)
    at Zy (http://localhost:8082/petclinic/main.28aace44eda54d8098cf.js:1:448060)
    at lv (http://localhost:8082/petclinic/main.28aace44eda54d8098cf.js:1:454982)
    at ov (http://localhost:8082/petclinic/main.28aace44eda54d8098cf.js:1:454645)
    at Zy (http://localhost:8082/petclinic/main.28aace44eda54d8098cf.js:1:448060)
    at lv (http://localhost:8082/petclinic/main.28aace44eda54d8098cf.js:1:454982)","message":"Cannot read property 'vlm' of undefined","name":"TypeError","logData":"Uncaught Exception"
}
```

### Code Snippet
```java
@MapsTo.Type(MealInstruction.class)
@Getter @Setter @ToString
public class MealInstructionLineItem {
	
	@Label("Food Name")
	@GridColumn(placeholder = "--")
	@Path
	private String name;
	
	@LinkMenu
	private VLM vlm;
 	
	@Model
	@Getter @Setter
	public static class VLM {
		
		@Label("Edit")
		@Link
		@Config(url = "/vpAddEditPet/vtAddEditPet/vmMealInstruction/section/form/_get?fn=param&expr=assignMapsTo('/.d/<!#this!>/../../.m')")
		@Config(url = "/vpAddEditPet/vtAddEditPet/vmMealInstruction/_process?fn=_setByRule&rule=togglemodal")
		private String edit;
		
		@Label("Remove")
		@Link
		@Config(url = "<!#this!>/../../_delete")
		private String remove;
	}
}
```

```java
@Label("Meal Instructions")
@Grid(onLoad = true, expandableRows = true)
@Path
private List<MealInstructionLineItem> mealInstructions;
```

# Environment Details
* **Nimbus Version:**
1.3.1.M1

* **Browser:**
Google Chrome

**Comment by lopezton-anthem** [comment]
Fix checked into 1.3.0.M2.
