### ISSUE TITLE
Console errors with "path of undefined" from @Link component

### ISSUE THREAD

**Issue by addulaajayreddy** [openanthem/nimbus-core#555]
# Issue Details

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
When `@Link` is configured in many places the browser is intermittently throwing a console error with a message of:
```json
{
    "stack": "TypeError: Cannot read property 'path' of undefined
        at t._next (http://localhost:8082/ltss/main.56f07456cefe1202083d.js:1:1874390)
        at t.__tryOrUnsub (http://localhost:8082/ltss/main.56f07456cefe1202083d.js:1:601069)
        at t.next (http://localhost:8082/ltss/main.56f07456cefe1202083d.js:1:600214)
        at t._next (http://localhost:8082/ltss/main.56f07456cefe1202083d.js:1:599228)
        at t.next (http://localhost:8082/ltss/main.56f07456cefe1202083d.js:1:598899)
        at t.next (http://localhost:8082/ltss/main.56f07456cefe1202083d.js:1:769065)
        at e.updateParam (http://localhost:8082/ltss/main.56f07456cefe1202083d.js:1:1271826)
        at e.traverseParam (http://localhost:8082/ltss/main.56f07456cefe1202083d.js:1:1271645)
        at e.processModelEvent (http://localhost:8082/ltss/main.56f07456cefe1202083d.js:1:1270682)
        at http://localhost:8082/ltss/main.56f07456cefe1202083d.js:1:1268900",
    "message": "Cannot read property 'path' of undefined",
    "name": "TypeError",
    "logData": "Uncaught Exception"
}
```

## Expected Behavior
A console error should not be thrown.

# Environment Details
* **Nimbus Version:**
1.3.0.M6

* **Browser:**
Chrome

**Comment by lopezton-anthem** [comment]
Thanks for your issue request.

In order to address the issue you're facing, please provide the more details on how to recreate the issue. If you're unsure of which details to provide, we've provided a handy issue template [here](https://github.com/openanthem/nimbus-core/blob/master/.github/issue_template.md).

**Comment by lopezton-anthem** [comment]
@sandeepmantha or I will fill the issue in with the necessary details. Please ignore the previous request for more detail. This is for our tracking.

**Comment by lopezton-anthem** [comment]
This change is in 1.3.x, will either go to 1.3.1.M3 if requested, or else 1.3.2.M1 (next scheduled release)

**Comment by addulaajayreddy** [comment]
Please merge this in 1.3.1.M3. Thanks
