### ISSUE TITLE
_new calls with JPA nullable=true causes ConstraintViolationException

### ISSUE THREAD

**Issue by lopezton-anthem** [openanthem/nimbus-core#641]
# Issue Details

**Type of Issue**  (check one with "X")
```
[X] Bug Report => Please search GitHub for a similar issue or PR before submitting
[ ] Feature Request => Please ensure feature is not already in progress
[ ] Support Request => Please do not submit support requests here, instead see: https://discourse.oss.antheminc.com/
```

## Current Behavior
When issuing a `_new` call on a domain entity that has fields configured like the following:
```java
@Domain(value = "sample_entity", includeListeners = ListenerType.persistence)
@Repo(value = Database.rep_rdbms)
@Table(name = "SAMPLE_ENTITY")
@Entity
@Access(AccessType.FIELD)
@Getter @Setter
public class SampleEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @Column
    @GeneratedValue(generator=SEQ_GEN_NAME)
    @GenericGenerator(name=SEQ_GEN_NAME, strategy=SEQ_GEN_STRATEGY,    parameters=@Parameter(name=SEQ_GEN_PARAM_K_NM, value="SEQ_ID"))
    private Long id;

    @Column(nullable = false)
    private Long v1;

    @Column(nullable = false)
    private Long v2;
}
```

with a payload of:

```json
{
    "v1": 42,
    "v2": 43
}
```

the `ParamStateAtomicPersistenceEventListener` seems to get an update for the following events:

* `/p/sample_entity/v1/_replace`, rawPayload = `42`
* `/p/sample_entity/v2/_replace`, rawPayload = `43`

The issue comes on the initial event of `v1`, where `ParamStateAtomicPersistenceEventListener` updates the root for `sample_entity` with the following:

```json
{
    "v1": 42
}
```

This causes the following exception

```sh
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:149) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:164) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1443) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1423) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:305) ~[spring-orm-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at com.sun.proxy.$Proxy217.flush(Unknown Source) ~[na:na]
	at com.antheminc.oss.nimbus.domain.model.state.repo.db.rdbms.DefaultJpaModelRepository._save(DefaultJpaModelRepository.java:248) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.repo.db.rdbms.DefaultJpaModelRepository._update(DefaultJpaModelRepository.java:223) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.repo.db.rdbms.DefaultJpaModelRepository$$FastClassBySpringCGLIB$$48bc5d9c.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at com.antheminc.oss.nimbus.support.DefaultLoggingInterceptor.logMethods(DefaultLoggingInterceptor.java:106) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) ~[spring-tx-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) ~[spring-tx-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at com.antheminc.oss.nimbus.domain.model.state.repo.db.rdbms.DefaultJpaModelRepository$$EnhancerBySpringCGLIB$$4c0e2dbf._update(<generated>) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.repo.db.ParamStateAtomicPersistenceEventListener.listen(ParamStateAtomicPersistenceEventListener.java:85) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.repo.db.AbstractStateAndConfigEventListener.listen(AbstractStateAndConfigEventListener.java:1) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.event.listener.QuadScopedEventListener.lambda$3(QuadScopedEventListener.java:64) ~[classes/:na]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_131]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_131]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_131]
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235) ~[na:1.8.0_131]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_131]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_131]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_131]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_131]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_131]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_131]
	at com.antheminc.oss.nimbus.domain.model.state.event.listener.QuadScopedEventListener.listen(QuadScopedEventListener.java:64) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.event.listener.QuadScopedEventListener.listen(QuadScopedEventListener.java:1) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.internal.AbstractEntityState.emitEvent(AbstractEntityState.java:242) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.internal.DefaultParamState.affectSetStateChange(DefaultParamState.java:397) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.internal.DefaultParamState.lambda$0(DefaultParamState.java:353) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.internal.AbstractEntityState.changeStateTemplate(AbstractEntityState.java:177) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.internal.DefaultParamState.setState(DefaultParamState.java:353) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.repo.ParamStateRepositoryGateway._setNestedModel(ParamStateRepositoryGateway.java:392) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.repo.ParamStateRepositoryGateway._set(ParamStateRepositoryGateway.java:295) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.repo.ParamStateRepositoryGateway._set(ParamStateRepositoryGateway.java:230) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.internal.DefaultParamState.affectSetStateChange(DefaultParamState.java:370) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.internal.DefaultParamState.lambda$0(DefaultParamState.java:353) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.internal.AbstractEntityState.changeStateTemplate(AbstractEntityState.java:177) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.model.state.internal.DefaultParamState.setState(DefaultParamState.java:353) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.cmd.exec.internal.DefaultActionExecutorNew.setStateNew(DefaultActionExecutorNew.java:113) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.cmd.exec.internal.DefaultActionExecutorNew.executeInternal(DefaultActionExecutorNew.java:89) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.cmd.exec.AbstractCommandExecutor.execute(AbstractCommandExecutor.java:74) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.cmd.exec.internal.DefaultCommandExecutorGateway.lambda$4(DefaultCommandExecutorGateway.java:439) ~[classes/:na]
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235) ~[na:1.8.0_131]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_131]
	at com.antheminc.oss.nimbus.domain.cmd.exec.internal.DefaultCommandExecutorGateway.executeSelf(DefaultCommandExecutorGateway.java:409) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.cmd.exec.internal.DefaultCommandExecutorGateway.executeInternal(DefaultCommandExecutorGateway.java:230) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.cmd.exec.internal.DefaultCommandExecutorGateway.execute(DefaultCommandExecutorGateway.java:155) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.cmd.exec.internal.DefaultCommandExecutorGateway.execute(DefaultCommandExecutorGateway.java:132) ~[classes/:na]
	at com.antheminc.oss.nimbus.domain.cmd.exec.internal.DefaultCommandExecutorGateway$$FastClassBySpringCGLIB$$72803a50.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at com.antheminc.oss.nimbus.support.DefaultLoggingInterceptor.logMethods(DefaultLoggingInterceptor.java:106) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor86.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:174) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at com.antheminc.oss.nimbus.domain.cmd.exec.internal.DefaultCommandExecutorGateway$$EnhancerBySpringCGLIB$$d4add020.execute(<generated>) ~[classes/:na]
...
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:112) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3032) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3547) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:89) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:600) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:474) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1437) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	... 128 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: NULL not allowed for column "V2"; SQL statement:
/* insert com.sample.SampleEntity */ insert into SAMPLE_ENTITY (V1, V2) values (?, ?) [23502-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.message.DbException.get(DbException.java:179) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.message.DbException.get(DbException.java:155) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:374) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:798) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.command.dml.Insert.insertRows(Insert.java:177) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.command.dml.Insert.update(Insert.java:134) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.command.CommandContainer.update(CommandContainer.java:102) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.command.Command.executeUpdate(Command.java:261) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199) ~[h2-1.4.197.jar:1.4.197]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153) ~[h2-1.4.197.jar:1.4.197]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97) ~[commons-dbcp2-2.2.0.jar:2.2.0]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	... 136 common frames omitted
```

## Expected Behavior
`@Column(nullable = false)` should not cause an exception when issuing a `_new` call.

# Environment Details
* **Nimbus Version:** 2.0.0.BUILD-SNAPSHOT

**Comment by lopezton-anthem** [comment]
Need to validate if this is still an issue when `nimbus.domain.model.persistence.strategy.mode` is set to `MANUAL`.
